// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef ui_trainer_h
#define ui_trainer_h
#include <FL/Fl.H>
#include <fstream>
#include "Interface.h"
#include "UI/IPInput.h"
#include "UI/Common.h"
#include "TrainerTable.h"
class Interface;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>

class TrainerClass {
public:
  static TrainerClass *uiInstance; 
  Fl_Text_Buffer ui_infoBuffer; 
  TrainerClass();
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  TrainerTable *ui_trainerTable;
  IPInput *ui_ipInput;
  Fl_Light_Button *ui_connectButton;
  Fl_Choice *ui_ccapiChoice;
  static Fl_Menu_Item menu_ui_ccapiChoice[];
  static Fl_Menu_Item *ui_ccapiVersion25Item;
  static Fl_Menu_Item *ui_ccapiVersion20Item;
  Fl_Box *ui_opStatus;
  Fl_Text_Display *ui_infoBox;
  static void CanConnectCB(Fl_Widget *w, void *data);
  static void ConnectButtonCB(Fl_Widget *w, void *data);
  void readIP();
  void storeIP();
  void setConnectStatus(char status);
  static void TrainButtonCB(Fl_Widget *w, void *data);
  void center(Fl_Widget *w);
};
#endif
