// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "ui_trainer.h"

Fl_Double_Window* TrainerClass::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(696, 655, "Trainer Title");
    w = o;
    o->user_data((void*)(this));
    { Fl_Table* o = new Fl_Table(5, 245, 685, 400);
      o->end();
    } // Fl_Table* o
    { new Fl_Box(10, 74, 675, 157, "Trainer Info");
    } // Fl_Box* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
