// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef ui_trainer_h
#define ui_trainer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Box.H>

class TrainerClass {
public:
  Fl_Double_Window* make_window();
};
#endif
